version: '3.8'

services:
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://<user>:<password>@<host>:<port>/<database>?schema=<schema>
    ports:
      - "3000:3000"